export const musclesValues = [
  'All',
  'Chest',
  'Lats',
  'Quads',
  'Shoulders',
  'Glutes',
  'Calves',
  'Hamstrings',
  'Abs',
  'Triceps',
  'Biceps',
  'Forearms',
  'Hip Adductors',
  'Lower Back',
  'Upper Back',
]

export const musclesImgs = [
  { value: 'All', src: '/muscles/all.webp' },
  { value: 'Chest', src: '/muscles/chest.webp' },
  { value: 'Lats', src: '/muscles/lats.webp' },
  { value: 'Quads', src: '/muscles/quads.webp' },
  { value: 'Glutes', src: '/muscles/glutes.webp' },
  { value: 'Calves', src: '/muscles/calves.webp' },
  { value: 'Hamstrings', src: '/muscles/hamstrings.webp' },
  { value: 'Abs', src: '/muscles/abs.webp' },
  { value: 'Shoulders', src: '/muscles/shoulders.webp' },
  { value: 'Triceps', src: '/muscles/triceps.webp' },
  { value: 'Biceps', src: '/muscles/biceps.webp' },
  { value: 'Forearms', src: '/muscles/forearms.webp' },
  { value: 'Hip Adductors', src: '/muscles/hip-adductors.webp' },
  { value: 'Lower Back', src: '/muscles/lower-back.webp' },
  { value: 'Upper Back', src: '/muscles/upper-back.webp' },
]
