export const POPULAR_EXERCISES = [
  {
    exerciseId: 'SpYC0Kp',
    name: 'dumbbell bench press',
    gifUrl: 'https://static.exercisedb.dev/media/SpYC0Kp.gif',
    targetMuscles: ['pectorals'],
    bodyParts: ['chest'],
    equipments: ['dumbbell'],
    secondaryMuscles: ['triceps', 'shoulders'],
    instructions: [
      'Step:1 Lie flat on a bench with your feet flat on the ground and your back pressed against the bench.',
      'Step:2 Hold a dumbbell in each hand, with your palms facing forward and your arms extended above your chest.',
      'Step:3 Lower the dumbbells slowly to the sides of your chest, keeping your elbows at a 90-degree angle.',
      'Step:4 Pause for a moment, then push the dumbbells back up to the starting position, fully extending your arms.',
      'Step:5 Repeat for the desired number of repetitions.',
    ],
  },

  {
    exerciseId: 'trqKQv2',
    name: 'smith bench press',
    gifUrl: 'https://static.exercisedb.dev/media/trqKQv2.gif',
    targetMuscles: ['pectorals'],
    bodyParts: ['chest'],
    equipments: ['smith machine'],
    secondaryMuscles: ['triceps', 'shoulders'],
    instructions: [
      'Step:1 Adjust the height of the smith machine bar to chest level.',
      'Step:2 Lie flat on the bench with your feet firmly planted on the ground.',
      'Step:3 Grip the bar with an overhand grip slightly wider than shoulder-width apart.',
      'Step:4 Unrack the bar and lower it towards your chest, keeping your elbows tucked in.',
      'Step:5 Pause for a moment when the bar touches your chest.',
      'Step:6 Push the bar back up to the starting position, fully extending your arms.',
      'Step:7 Repeat for the desired number of repetitions.',
    ],
  },
  {
    exerciseId: 'znQUdHY',
    name: 'dumbbell seated shoulder press',
    gifUrl: 'https://static.exercisedb.dev/media/znQUdHY.gif',
    targetMuscles: ['delts'],
    bodyParts: ['shoulders'],
    equipments: ['dumbbell'],
    secondaryMuscles: ['triceps', 'upper back'],
    instructions: [
      'Step:1 Sit on a bench with a dumbbell in each hand, resting on your thighs.',
      'Step:2 Raise the dumbbells to shoulder height, palms facing forward.',
      'Step:3 Press the dumbbells upward until your arms are fully extended overhead.',
      'Step:4 Pause for a moment at the top, then slowly lower the dumbbells back to shoulder height.',
      'Step:5 Repeat for the desired number of repetitions.',
    ],
  },
  {
    exerciseId: 'EIeI8Vf',
    name: 'barbell bench press',
    gifUrl: 'https://static.exercisedb.dev/media/EIeI8Vf.gif',
    targetMuscles: ['pectorals'],
    bodyParts: ['chest'],
    equipments: ['barbell'],
    secondaryMuscles: ['triceps', 'shoulders'],
    instructions: [
      'Step:1 Lie flat on a bench with your feet flat on the ground and your back pressed against the bench.',
      'Step:2 Grasp the barbell with an overhand grip slightly wider than shoulder-width apart.',
      'Step:3 Lift the barbell off the rack and hold it directly above your chest with your arms fully extended.',
      'Step:4 Lower the barbell slowly towards your chest, keeping your elbows tucked in.',
      'Step:5 Pause for a moment when the barbell touches your chest.',
      'Step:6 Push the barbell back up to the starting position by extending your arms.',
      'Step:7 Repeat for the desired number of repetitions.',
    ],
  },

  {
    exerciseId: 'yz9nUhF',
    name: 'dumbbell fly',
    gifUrl: 'https://static.exercisedb.dev/media/yz9nUhF.gif',
    targetMuscles: ['pectorals'],
    bodyParts: ['chest'],
    equipments: ['dumbbell'],
    secondaryMuscles: ['shoulders'],
    instructions: [
      'Step:1 Lie flat on a bench with a dumbbell in each hand, palms facing each other.',
      'Step:2 Extend your arms straight up over your chest, with a slight bend in your elbows.',
      'Step:3 Keeping a slight bend in your elbows, lower your arms out to the sides in a wide arc until you feel a stretch in your chest.',
      'Step:4 Pause for a moment, then reverse the movement and bring the dumbbells back up to the starting position.',
      'Step:5 Repeat for the desired number of repetitions.',
    ],
  },
  {
    exerciseId: 'xLYSdtg',
    name: 'cable middle fly',
    gifUrl: 'https://static.exercisedb.dev/media/xLYSdtg.gif',
    targetMuscles: ['pectorals'],
    bodyParts: ['chest'],
    equipments: ['cable'],
    secondaryMuscles: ['deltoids', 'triceps'],
    instructions: [
      'Step:1 Attach cables to both sides of a cable machine at chest height.',
      'Step:2 Stand in the center of the machine with one foot slightly in front of the other.',
      'Step:3 Grasp the handles with an overhand grip and extend your arms out to the sides.',
      'Step:4 Keep a slight bend in your elbows and maintain a slight forward lean.',
      'Step:5 Engage your chest muscles and bring your arms forward in a sweeping motion.',
      'Step:6 Pause for a moment at the center, then slowly return your arms back to the starting position.',
      'Step:7 Repeat for the desired number of repetitions.',
    ],
  },
  {
    exerciseId: 'EAs3xL9',
    name: 'dumbbell reverse fly',
    gifUrl: 'https://static.exercisedb.dev/media/EAs3xL9.gif',
    targetMuscles: ['delts'],
    bodyParts: ['shoulders'],
    equipments: ['dumbbell'],
    secondaryMuscles: ['trapezius', 'rhomboids'],
    instructions: [
      'Step:1 Stand with your feet shoulder-width apart and hold a dumbbell in each hand.',
      'Step:2 Bend your knees slightly and hinge forward at the hips, keeping your back straight.',
      'Step:3 Extend your arms straight down in front of you, palms facing each other.',
      'Step:4 Keeping a slight bend in your elbows, raise your arms out to the sides until they are parallel to the ground.',
      'Step:5 Pause for a moment at the top, then slowly lower your arms back down to the starting position.',
      'Step:6 Repeat for the desired number of repetitions.',
    ],
  },

  {
    exerciseId: 'eZyBC3j',
    name: 'barbell bent over row',
    gifUrl: 'https://static.exercisedb.dev/media/eZyBC3j.gif',
    targetMuscles: ['upper back'],
    bodyParts: ['back'],
    equipments: ['barbell'],
    secondaryMuscles: ['biceps', 'forearms'],
    instructions: [
      'Step:1 Stand with your feet shoulder-width apart and knees slightly bent.',
      'Step:2 Bend forward at the hips while keeping your back straight and chest up.',
      'Step:3 Grasp the barbell with an overhand grip, hands slightly wider than shoulder-width apart.',
      'Step:4 Pull the barbell towards your lower chest by retracting your shoulder blades and squeezing your back muscles.',
      'Step:5 Pause for a moment at the top, then slowly lower the barbell back to the starting position.',
      'Step:6 Repeat for the desired number of repetitions.',
    ],
  },

  {
    exerciseId: 'NbVPDMW',
    name: 'dumbbell biceps curl',
    gifUrl: 'https://static.exercisedb.dev/media/NbVPDMW.gif',
    targetMuscles: ['biceps'],
    bodyParts: ['upper arms'],
    equipments: ['dumbbell'],
    secondaryMuscles: ['forearms'],
    instructions: [
      'Step:1 Stand up straight with a dumbbell in each hand, palms facing forward and arms fully extended.',
      'Step:2 Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps.',
      'Step:3 Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level.',
      'Step:4 Hold the contracted position for a brief pause as you squeeze your biceps.',
      'Step:5 Inhale and slowly begin to lower the dumbbells back to the starting position.',
      'Step:6 Repeat for the desired number of repetitions.',
    ],
  },

  {
    exerciseId: 'ila4NZS',
    name: 'barbell deadlift',
    gifUrl: 'https://static.exercisedb.dev/media/ila4NZS.gif',
    targetMuscles: ['glutes'],
    bodyParts: ['upper legs'],
    equipments: ['barbell'],
    secondaryMuscles: ['hamstrings', 'lower back'],
    instructions: [
      'Step:1 Stand with your feet shoulder-width apart and the barbell on the ground in front of you.',
      'Step:2 Bend your knees and hinge at the hips to lower your torso and grip the barbell with an overhand grip, hands slightly wider than shoulder-width apart.',
      'Step:3 Keep your back straight and chest lifted as you drive through your heels to lift the barbell off the ground, extending your hips and knees.',
      'Step:4 As you stand up straight, squeeze your glutes and keep your core engaged.',
      'Step:5 Lower the barbell back down to the ground by bending at the hips and knees, keeping your back straight.',
      'Step:6 Repeat for the desired number of repetitions.',
    ],
  },
  {
    exerciseId: 'wQ2c4XD',
    name: 'barbell romanian deadlift',
    gifUrl: 'https://static.exercisedb.dev/media/wQ2c4XD.gif',
    targetMuscles: ['glutes'],
    bodyParts: ['upper legs'],
    equipments: ['barbell'],
    secondaryMuscles: ['hamstrings', 'lower back'],
    instructions: [
      'Step:1 Stand with your feet shoulder-width apart and your toes pointing forward.',
      'Step:2 Hold the barbell with an overhand grip, hands slightly wider than shoulder-width apart.',
      'Step:3 Bend at the hips, keeping your back straight and your knees slightly bent.',
      'Step:4 Lower the barbell towards the ground, keeping it close to your body.',
      'Step:5 Feel the stretch in your hamstrings as you lower the barbell.',
      'Step:6 Once you feel a stretch in your hamstrings, push your hips forward and stand up straight.',
      'Step:7 Squeeze your glutes at the top of the movement.',
      'Step:8 Lower the barbell back down to the starting position and repeat for the desired number of repetitions.',
    ],
  },
  {
    exerciseId: 'KgI0tqW',
    name: 'barbell sumo deadlift',
    gifUrl: 'https://static.exercisedb.dev/media/KgI0tqW.gif',
    targetMuscles: ['glutes'],
    bodyParts: ['upper legs'],
    equipments: ['barbell'],
    secondaryMuscles: ['hamstrings', 'quadriceps', 'lower back'],
    instructions: [
      'Step:1 Stand with your feet wider than shoulder-width apart, toes pointing outwards.',
      'Step:2 Place a barbell on the ground in front of you, centered between your feet.',
      'Step:3 Bend your knees and lower your hips, keeping your back straight and chest up, to grip the barbell with an overhand grip.',
      'Step:4 Engage your core and drive through your heels to lift the barbell off the ground, extending your hips and knees simultaneously.',
      'Step:5 As you lift, keep your chest up and back straight, and push your hips forward to fully engage your glutes.',
      'Step:6 Pause for a moment at the top, then slowly lower the barbell back down to the starting position, maintaining control throughout the movement.',
      'Step:7 Repeat for the desired number of repetitions.',
    ],
  },
  {
    exerciseId: 'rR0LJzx',
    name: 'dumbbell romanian deadlift',
    gifUrl: 'https://static.exercisedb.dev/media/rR0LJzx.gif',
    targetMuscles: ['glutes'],
    bodyParts: ['upper legs'],
    equipments: ['dumbbell'],
    secondaryMuscles: ['hamstrings', 'lower back'],
    instructions: [
      'Step:1 Stand with your feet shoulder-width apart, holding a dumbbell in each hand with an overhand grip.',
      'Step:2 Keeping your back straight and your core engaged, hinge at the hips and lower the dumbbells towards the ground, allowing your knees to bend slightly.',
      'Step:3 Lower the dumbbells until you feel a stretch in your hamstrings, then push through your heels and engage your glutes to return to the starting position.',
      'Step:4 Repeat for the desired number of repetitions.',
    ],
  },

  {
    exerciseId: 'slDvUAU',
    name: 'dumbbell hammer curl',
    gifUrl: 'https://static.exercisedb.dev/media/slDvUAU.gif',
    targetMuscles: ['biceps'],
    bodyParts: ['upper arms'],
    equipments: ['dumbbell'],
    secondaryMuscles: ['forearms'],
    instructions: [
      'Step:1 Stand up straight with a dumbbell in each hand, palms facing your torso.',
      'Step:2 Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward.',
      'Step:3 This will be your starting position.',
      'Step:4 Now, keeping the upper arms stationary, exhale and curl the weights while contracting your biceps.',
      'Step:5 Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level.',
      'Step:6 Hold the contracted position for a brief pause as you squeeze your biceps.',
      'Step:7 Then, inhale and slowly begin to lower the dumbbells back to the starting position.',
      'Step:8 Repeat for the recommended amount of repetitions.',
    ],
  },
  {
    exerciseId: 'F1KxjBa',
    name: 'dumbbell peacher hammer curl',
    gifUrl: 'https://static.exercisedb.dev/media/F1KxjBa.gif',
    targetMuscles: ['biceps'],
    bodyParts: ['upper arms'],
    equipments: ['dumbbell'],
    secondaryMuscles: ['forearms'],
    instructions: [
      'Step:1 Stand up straight with a dumbbell in each hand, palms facing your torso.',
      'Step:2 Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward.',
      'Step:3 This will be your starting position.',
      'Step:4 Now, keeping the upper arms stationary, exhale and curl the weights while contracting your biceps.',
      'Step:5 Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level.',
      'Step:6 Hold the contracted position for a brief pause as you squeeze your biceps.',
      'Step:7 Then, inhale and slowly begin to lower the dumbbells back to the starting position.',
      'Step:8 Repeat for the recommended amount of repetitions.',
    ],
  },

  {
    exerciseId: '3TZduzM',
    name: 'barbell incline bench press',
    gifUrl: 'https://static.exercisedb.dev/media/3TZduzM.gif',
    targetMuscles: ['pectorals'],
    bodyParts: ['chest'],
    equipments: ['barbell'],
    secondaryMuscles: ['shoulders', 'triceps'],
    instructions: [
      'Step:1 Set up an incline bench at a 45-degree angle.',
      'Step:2 Lie down on the bench with your feet flat on the ground.',
      'Step:3 Grasp the barbell with an overhand grip, slightly wider than shoulder-width apart.',
      'Step:4 Unrack the barbell and lower it slowly towards your chest, keeping your elbows at a 45-degree angle.',
      'Step:5 Pause for a moment at the bottom, then push the barbell back up to the starting position.',
      'Step:6 Repeat for the desired number of repetitions.',
    ],
  },
  {
    exerciseId: '5v7KYld',
    name: 'smith incline bench press',
    gifUrl: 'https://static.exercisedb.dev/media/5v7KYld.gif',
    targetMuscles: ['pectorals'],
    bodyParts: ['chest'],
    equipments: ['smith machine'],
    secondaryMuscles: ['shoulders', 'triceps'],
    instructions: [
      'Step:1 Adjust the bench to a 30-45 degree incline.',
      'Step:2 Sit on the bench with your back flat against the pad and feet firmly on the ground.',
      'Step:3 Grasp the barbell with an overhand grip slightly wider than shoulder-width apart.',
      'Step:4 Unrack the barbell and lower it slowly towards your upper chest, keeping your elbows slightly tucked in.',
      'Step:5 Pause for a moment at the bottom, then push the barbell back up to the starting position, fully extending your arms.',
      'Step:6 Repeat for the desired number of repetitions.',
    ],
  },

  {
    exerciseId: 'ns0SIbU',
    name: 'dumbbell incline bench press',
    gifUrl: 'https://static.exercisedb.dev/media/ns0SIbU.gif',
    targetMuscles: ['pectorals'],
    bodyParts: ['chest'],
    equipments: ['dumbbell'],
    secondaryMuscles: ['shoulders', 'triceps'],
    instructions: [
      'Step:1 Set up an incline bench at a 45-degree angle.',
      'Step:2 Sit on the bench with your feet flat on the ground and your back pressed firmly against the bench.',
      'Step:3 Hold a dumbbell in each hand, palms facing forward, and lift them to shoulder height.',
      'Step:4 Slowly lower the dumbbells to the sides of your chest, keeping your elbows at a 90-degree angle.',
      'Step:5 Push the dumbbells back up to the starting position, fully extending your arms.',
      'Step:6 Repeat for the desired number of repetitions.',
    ],
  },

  {
    exerciseId: 'RVwzP10',
    name: 'cable pulldown',
    gifUrl: 'https://static.exercisedb.dev/media/RVwzP10.gif',
    targetMuscles: ['lats'],
    bodyParts: ['back'],
    equipments: ['cable'],
    secondaryMuscles: ['biceps', 'forearms'],
    instructions: [
      'Step:1 Adjust the cable pulldown machine so that the seat is at a comfortable height and the knee pad is secured.',
      'Step:2 Sit on the seat with your back straight and your feet flat on the ground.',
      'Step:3 Grasp the cable bar with an overhand grip, slightly wider than shoulder-width apart.',
      'Step:4 Lean back slightly and engage your core.',
      'Step:5 Pull the cable bar down towards your chest, squeezing your shoulder blades together.',
      'Step:6 Pause for a moment at the bottom of the movement, then slowly release the bar back to the starting position.',
      'Step:7 Repeat for the desired number of repetitions.',
    ],
  },

  {
    exerciseId: 'DsgkuIt',
    name: 'dumbbell lateral raise',
    gifUrl: 'https://static.exercisedb.dev/media/DsgkuIt.gif',
    targetMuscles: ['delts'],
    bodyParts: ['shoulders'],
    equipments: ['dumbbell'],
    secondaryMuscles: ['traps'],
    instructions: [
      'Step:1 Stand with your feet shoulder-width apart and hold a dumbbell in each hand, palms facing your body.',
      'Step:2 Keep your back straight and engage your core.',
      'Step:3 Raise your arms out to the sides until they are parallel to the floor, keeping a slight bend in your elbows.',
      'Step:4 Pause for a moment at the top, then slowly lower your arms back down to the starting position.',
      'Step:5 Repeat for the desired number of repetitions.',
    ],
  },

  {
    exerciseId: 'my33uHU',
    name: 'lever leg extension',
    gifUrl: 'https://static.exercisedb.dev/media/my33uHU.gif',
    targetMuscles: ['quads'],
    bodyParts: ['upper legs'],
    equipments: ['leverage machine'],
    secondaryMuscles: ['hamstrings'],
    instructions: [
      'Step:1 Adjust the seat height and backrest of the machine to fit your body.',
      'Step:2 Sit on the machine with your back against the backrest and your feet on the footpad.',
      'Step:3 Grasp the handles or sidebars for stability.',
      'Step:4 Extend your legs forward by straightening your knees, lifting the weight.',
      'Step:5 Pause for a moment at the top, then slowly lower the weight back to the starting position.',
      'Step:6 Repeat for the desired number of repetitions.',
    ],
  },

  {
    exerciseId: '7zdxRTl',
    name: 'smith leg press',
    gifUrl: 'https://static.exercisedb.dev/media/7zdxRTl.gif',
    targetMuscles: ['glutes'],
    bodyParts: ['upper legs'],
    equipments: ['smith machine'],
    secondaryMuscles: ['quadriceps', 'hamstrings', 'calves'],
    instructions: [
      'Step:1 Adjust the seat and footplate of the smith machine to a comfortable position.',
      'Step:2 Sit on the machine with your back against the backrest and your feet shoulder-width apart on the footplate.',
      'Step:3 Grasp the handles or sides of the machine for stability.',
      'Step:4 Push the footplate away from you by extending your legs, keeping your back against the backrest.',
      'Step:5 Pause for a moment at the fully extended position.',
      'Step:6 Slowly bend your knees and lower the footplate back towards you, returning to the starting position.',
      'Step:7 Repeat for the desired number of repetitions.',
    ],
  },
  {
    exerciseId: '10Z2DXU',
    name: 'sled 45в° leg press',
    gifUrl: 'https://static.exercisedb.dev/media/10Z2DXU.gif',
    targetMuscles: ['glutes'],
    bodyParts: ['upper legs'],
    equipments: ['sled machine'],
    secondaryMuscles: ['quadriceps', 'hamstrings', 'calves'],
    instructions: [
      'Step:1 Adjust the seat and footplate of the sled machine to a comfortable position.',
      'Step:2 Sit on the sled machine with your back against the backrest and your feet shoulder-width apart on the footplate.',
      'Step:3 Grip the handles on the sides of the seat for stability.',
      'Step:4 Push the footplate away from your body by extending your legs, keeping your heels on the footplate.',
      'Step:5 Continue pushing until your legs are almost fully extended, but without locking your knees.',
      'Step:6 Pause for a moment at the top of the movement, then slowly lower the footplate back towards your body by bending your knees.',
      'Step:7 Repeat for the desired number of repetitions.',
    ],
  },

  {
    exerciseId: '17lJ1kr',
    name: 'lever lying leg curl',
    gifUrl: 'https://static.exercisedb.dev/media/17lJ1kr.gif',
    targetMuscles: ['hamstrings'],
    bodyParts: ['upper legs'],
    equipments: ['leverage machine'],
    secondaryMuscles: ['calves'],
    instructions: [
      'Step:1 Adjust the machine to fit your body and select the desired weight.',
      'Step:2 Lie face down on the machine with your legs straight and your heels against the padded lever.',
      'Step:3 Grasp the handles or the sides of the machine for stability.',
      'Step:4 Keeping your upper body stationary, exhale and curl your legs up as far as possible without lifting your hips off the pad.',
      'Step:5 Hold the contracted position for a brief pause as you squeeze your hamstrings.',
      'Step:6 Inhale and slowly lower the lever back to the starting position.',
      'Step:7 Repeat for the desired number of repetitions.',
    ],
  },
  {
    exerciseId: 'Zg3XY7P',
    name: 'lever seated leg curl',
    gifUrl: 'https://static.exercisedb.dev/media/Zg3XY7P.gif',
    targetMuscles: ['hamstrings'],
    bodyParts: ['upper legs'],
    equipments: ['leverage machine'],
    secondaryMuscles: ['calves'],
    instructions: [
      'Step:1 Adjust the machine to fit your body and sit on it with your back against the backrest.',
      'Step:2 Place your lower legs under the padded lever, just above your ankles.',
      'Step:3 Grasp the handles on the sides of the machine for support.',
      'Step:4 Keeping your upper legs stationary, exhale and curl your legs up as far as possible.',
      'Step:5 Hold the contracted position for a brief pause as you squeeze your hamstrings.',
      'Step:6 Inhale and slowly lower the lever back to the starting position.',
      'Step:7 Repeat for the desired number of repetitions.',
    ],
  },

  {
    exerciseId: 'hvV79Si',
    name: 'cable low seated row',
    gifUrl: 'https://static.exercisedb.dev/media/hvV79Si.gif',
    targetMuscles: ['upper back'],
    bodyParts: ['back'],
    equipments: ['cable'],
    secondaryMuscles: ['biceps', 'forearms'],
    instructions: [
      'Step:1 Sit on the machine with your feet flat on the footrests and your knees slightly bent.',
      'Step:2 Grasp the handles with an overhand grip, palms facing down.',
      'Step:3 Keep your back straight and lean slightly forward, maintaining a slight bend in your elbows.',
      'Step:4 Pull the handles towards your body, squeezing your shoulder blades together.',
      'Step:5 Pause for a moment at the peak of the movement, then slowly release the handles back to the starting position.',
      'Step:6 Repeat for the desired number of repetitions.',
    ],
  },

  {
    exerciseId: 'jFtipLl',
    name: 'smith squat',
    gifUrl: 'https://static.exercisedb.dev/media/jFtipLl.gif',
    targetMuscles: ['glutes'],
    bodyParts: ['upper legs'],
    equipments: ['smith machine'],
    secondaryMuscles: ['quadriceps', 'hamstrings', 'calves'],
    instructions: [
      'Step:1 Set up the smith machine with the barbell at an appropriate height for your squat.',
      'Step:2 Stand with your feet shoulder-width apart, toes slightly turned out.',
      'Step:3 Position yourself under the barbell, resting it on your upper traps and shoulders.',
      'Step:4 Grip the barbell with a wide grip, slightly wider than shoulder-width apart.',
      'Step:5 Engage your core and unrack the barbell, stepping back to clear the rack.',
      'Step:6 Keeping your chest up and back straight, initiate the squat by bending at the hips and knees.',
      'Step:7 Lower your body until your thighs are parallel to the ground or slightly below.',
      'Step:8 Pause for a moment at the bottom, then drive through your heels to return to the starting position.',
      'Step:9 Repeat for the desired number of repetitions.',
    ],
  },

  {
    exerciseId: 'kTbSH9h',
    name: 'barbell seated overhead press',
    gifUrl: 'https://static.exercisedb.dev/media/kTbSH9h.gif',
    targetMuscles: ['delts'],
    bodyParts: ['shoulders'],
    equipments: ['barbell'],
    secondaryMuscles: ['triceps', 'upper back'],
    instructions: [
      'Step:1 Sit on a bench with your back straight and feet flat on the ground.',
      'Step:2 Hold the barbell with an overhand grip, slightly wider than shoulder-width apart.',
      'Step:3 Lift the barbell off the rack and bring it to shoulder level, with your elbows bent and palms facing forward.',
      'Step:4 Press the barbell overhead by extending your arms fully.',
      'Step:5 Pause for a moment at the top, then slowly lower the barbell back to shoulder level.',
      'Step:6 Repeat for the desired number of repetitions.',
    ],
  },

  {
    exerciseId: 'gAwDzB3',
    name: 'cable triceps pushdown (v-bar)',
    gifUrl: 'https://static.exercisedb.dev/media/gAwDzB3.gif',
    targetMuscles: ['triceps'],
    bodyParts: ['upper arms'],
    equipments: ['cable'],
    secondaryMuscles: ['forearms'],
    instructions: [
      'Step:1 Attach a v-bar attachment to the cable machine at the highest setting.',
      'Step:2 Stand facing the cable machine with your feet shoulder-width apart.',
      'Step:3 Grasp the v-bar with an overhand grip, palms facing down, and your hands shoulder-width apart.',
      'Step:4 Keep your elbows close to your sides and your upper arms stationary throughout the exercise.',
      'Step:5 Engage your triceps and exhale as you push the v-bar down until your arms are fully extended.',
      'Step:6 Pause for a moment at the bottom of the movement, squeezing your triceps.',
      'Step:7 Inhale as you slowly return the v-bar to the starting position, maintaining control.',
      'Step:8 Repeat for the desired number of repetitions.',
    ],
  },

  {
    exerciseId: '6TG6x2w',
    name: 'ez barbell curl',
    gifUrl: 'https://static.exercisedb.dev/media/6TG6x2w.gif',
    targetMuscles: ['biceps'],
    bodyParts: ['upper arms'],
    equipments: ['ez barbell'],
    secondaryMuscles: ['forearms'],
    instructions: [
      'Step:1 Stand up straight with your feet shoulder-width apart and hold the ez barbell with an underhand grip, palms facing up.',
      'Step:2 Keep your elbows close to your torso and your upper arms stationary throughout the movement.',
      'Step:3 Exhale as you curl the barbell up towards your shoulders, contracting your biceps.',
      'Step:4 Pause for a moment at the top, then inhale as you slowly lower the barbell back down to the starting position.',
      'Step:5 Repeat for the desired number of repetitions.',
    ],
  },

  {
    exerciseId: 'h8LFzo9',
    name: 'barbell lying triceps extension skull crusher',
    gifUrl: 'https://static.exercisedb.dev/media/h8LFzo9.gif',
    targetMuscles: ['triceps'],
    bodyParts: ['upper arms'],
    equipments: ['barbell'],
    secondaryMuscles: ['shoulders'],
    instructions: [
      'Step:1 Lie flat on a bench with your feet flat on the ground and your head at the end of the bench.',
      'Step:2 Hold the barbell with an overhand grip, hands shoulder-width apart, and extend your arms straight up over your chest.',
      'Step:3 Keeping your upper arms stationary, slowly lower the barbell towards your forehead by bending your elbows.',
      'Step:4 Pause for a moment when the barbell is just above your forehead, then extend your arms back up to the starting position.',
      'Step:5 Repeat for the desired number of repetitions.',
    ],
  },

  {
    exerciseId: 'W9pFVv1',
    name: 'barbell bench squat',
    gifUrl: 'https://static.exercisedb.dev/media/W9pFVv1.gif',
    targetMuscles: ['quads'],
    bodyParts: ['upper legs'],
    equipments: ['barbell'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    instructions: [
      'Step:1 Set up a barbell on a squat rack at chest height.',
      'Step:2 Stand facing away from the rack, with your feet shoulder-width apart.',
      'Step:3 Bend your knees and lower your body down into a squat position, keeping your back straight and chest up.',
      'Step:4 Grasp the barbell with an overhand grip, slightly wider than shoulder-width apart.',
      'Step:5 Lift the barbell off the rack and step back, ensuring your feet are still shoulder-width apart.',
      'Step:6 Lower your body down into a squat, keeping your knees in line with your toes.',
      'Step:7 Pause for a moment at the bottom, then push through your heels to return to the starting position.',
      'Step:8 Repeat for the desired number of repetitions.',
    ],
  },

  {
    exerciseId: 'qXTaZnJ',
    name: 'barbell full squat',
    gifUrl: 'https://static.exercisedb.dev/media/qXTaZnJ.gif',
    targetMuscles: ['glutes'],
    bodyParts: ['upper legs'],
    equipments: ['barbell'],
    secondaryMuscles: ['quadriceps', 'hamstrings', 'calves', 'core'],
    instructions: [
      'Step:1 Stand with your feet shoulder-width apart, toes slightly turned out.',
      'Step:2 Hold the barbell across your upper back, resting it on your traps or rear delts.',
      'Step:3 Engage your core and keep your chest up as you begin to lower your body down.',
      'Step:4 Bend at the knees and hips, pushing your hips back and down as if sitting into a chair.',
      'Step:5 Lower yourself until your thighs are parallel to the ground or slightly below.',
      'Step:6 Keep your knees in line with your toes and your weight in your heels.',
      'Step:7 Drive through your heels to stand back up, extending your hips and knees.',
      'Step:8 Repeat for the desired number of repetitions.',
    ],
  },
]
